import React,{useState} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowRight,Brain,Users,MessageCircle,Target,CheckCircle2,Menu,X,Phone,Mail,ChevronRight,Sparkles,Briefcase,UserRound,Quote}from'lucide-react';
import'./styles.css';

const services=[
 {icon:Users,kicker:'FOR ORGANIZATIONS',title:'Workplace Behaviour Workshops',text:'Practical, conversation-led sessions designed around communication, self-awareness and everyday team behaviour.',points:['Customized for your team context','Interactive activities and reflection','Action-focused takeaways']},
 {icon:UserRound,kicker:'FOR PROFESSIONALS',title:'1:1 Behaviour Guidance',text:'A structured space to understand recurring patterns and translate personal insight into practical workplace actions.',points:['Individual reflection and analysis','Clear development priorities','Practical improvement plan']},
 {icon:Briefcase,kicker:'FOR HR & LEADERS',title:'Team Development Consulting',text:'Support for leaders who want a more thoughtful approach to communication, team dynamics and behaviour development.',points:['Discovery conversation','Need-based engagement design','Follow-through recommendations']}
];
const problems=[['Conversations get avoided','Important feedback stays unsaid until small issues become team issues.'],['Good people react under pressure','Capability is there, but stress changes communication and decision-making.'],['Training doesn’t always stick','A good session creates energy. Development needs a bridge from insight to daily behaviour.']];
const process=[['01','Understand','We begin with the person, team context and the behaviour challenge that matters.'],['02','Explore','We use guided analysis, reflection and activities to surface useful patterns and perspectives.'],['03','Develop','Insights are translated into practical actions that can be applied in real work situations.'],['04','Evolve','The focus stays on intentional improvement, reflection and sustainable behaviour change.']];
function App(){const[open,setOpen]=useState(false);const wa='https://wa.me/919911382917?text=Hello%20Sunil%2C%20I%27d%20like%20to%20know%20more%20about%20EvolvSigns.';return <>
<header><a className="brand" href="#top"><span className="mark">E</span><span>Evolv<span>Signs</span></span></a><nav className={open?'open':''}>{['Approach','Services','For Teams','About'].map(x=><a key={x} href={'#'+x.toLowerCase().replace(' ','-')} onClick={()=>setOpen(false)}>{x}</a>)}<a className="navcta" href={wa}>Book a conversation <ArrowRight size={16}/></a></nav><button className="menub" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>
<main id="top">
<section className="hero"><div className="grain"></div><div className="heroCopy"><div className="eyebrow"><Sparkles size={15}/> Behaviour insight. Practical development.</div><h1>Better teams begin with <em>better understanding.</em></h1><p className="lead">EvolvSigns helps professionals and organizations understand workplace behaviour and turn personal insights into practical development.</p><div className="actions"><a className="primary" href={wa}>Start a conversation <ArrowRight size={18}/></a><a className="secondary" href="#approach">Explore our approach <ChevronRight size={18}/></a></div><div className="micro"><span><CheckCircle2/> Professionals</span><span><CheckCircle2/> Teams</span><span><CheckCircle2/> HR & L&D</span></div></div>
<div className="heroVisual"><div className="portrait"><div className="portraitGlow"></div><div className="initials">SS</div><div className="nameplate"><small>FOUNDER • EVOLVSIGNS</small><strong>Sunil Saxena</strong><span>Behaviour Development Consultant</span></div></div><div className="floatcard fc1"><Brain/><span><small>FROM INSIGHT</small>Self-awareness</span></div><div className="floatcard fc2"><Target/><span><small>TO ACTION</small>Practical development</span></div></div></section>
<section className="statement"><p>Not personality labels. Not one-size-fits-all motivation.</p><h2>We turn <i>self-awareness</i> into workplace actions people can actually use.</h2></section>
<section className="problems" id="approach"><div className="sectionIntro"><span className="tag">WHY EVOLVSIGNS</span><h2>Workplace challenges are often <em>human</em> before they are technical.</h2><p>When communication, pressure and behaviour patterns get in the way, another generic presentation rarely solves the problem.</p></div><div className="problemGrid">{problems.map((p,i)=><article key={p[0]}><span>0{i+1}</span><h3>{p[0]}</h3><p>{p[1]}</p></article>)}</div></section>
<section className="services" id="services"><div className="sectionIntro light"><span className="tag">HOW WE CAN HELP</span><h2>Development designed around <em>real people and real work.</em></h2></div><div className="serviceGrid">{services.map(({icon:Icon,...s})=><article key={s.title}><div className="icon"><Icon/></div><small>{s.kicker}</small><h3>{s.title}</h3><p>{s.text}</p><ul>{s.points.map(x=><li key={x}><CheckCircle2/> {x}</li>)}</ul><a href={wa}>Discuss this service <ArrowRight/></a></article>)}</div></section>
<section className="method" id="for-teams"><div className="methodText"><span className="tag">THE EVOLVSIGNS METHOD</span><h2>Insight is only useful when it changes what happens <em>next.</em></h2><p>Our approach can include personality reflection and graphology as exploratory tools, followed by practical discussion and development activities. We do not present handwriting analysis as a scientific diagnosis or use it to determine job suitability.</p><a className="darklink" href={wa}>Plan a team discussion <ArrowRight/></a></div><div className="steps">{process.map(x=><div className="step" key={x[0]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div></div>)}</div></section>
<section className="audience"><span className="tag">BUILT FOR THE WORKPLACE</span><h2>Where EvolvSigns can add value</h2><div className="chips">{['Leadership communication','Feedback conversations','Self-awareness','Team dynamics','Handling pressure','Professional behaviour','Manager development','Workplace communication'].map(x=><span key={x}>{x}</span>)}</div></section>
<section className="about" id="about"><div className="aboutCard"><div className="avatar">SS</div><div><span className="tag">MEET THE FOUNDER</span><h2>Sunil Saxena</h2><h4>Founder, EvolvSigns</h4><p>Sunil’s work is centered on a simple idea: understanding yourself should lead to something useful. Through EvolvSigns, he brings personality exploration and practical behaviour development together for professionals, leaders and teams.</p><p className="placeholder">Founder biography shown here is introductory website copy and can be replaced with Sunil’s verified background, experience and credentials.</p><a href={wa}>Connect with Sunil <MessageCircle/></a></div></div></section>
<section className="cta"><div><span>READY TO START A USEFUL CONVERSATION?</span><h2>Tell us what’s happening in your team. We’ll explore what kind of support makes sense.</h2></div><a href={wa}>Book a discovery conversation <ArrowRight/></a></section>
</main>
<footer><div><a className="brand foot" href="#top"><span className="mark">E</span><span>Evolv<span>Signs</span></span></a><p>Understanding workplace behaviour. Turning insight into practical development.</p></div><div><b>Explore</b><a href="#approach">Our approach</a><a href="#services">Services</a><a href="#about">About Sunil</a></div><div><b>Contact</b><a href="tel:+919911382917"><Phone/> +91 99113 82917</a><a href="mailto:hello@evolvsigns.com"><Mail/> hello@evolvsigns.com</a><small>Demo email — replace before launch</small></div><div className="copyright">© {new Date().getFullYear()} EvolvSigns. All rights reserved.</div></footer>
<a className="whatsapp" href={wa} aria-label="WhatsApp"><MessageCircle/></a>
</>}
createRoot(document.getElementById('root')).render(<App/>);
